plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.handtracker'
version = '1.0.0'

android {
  namespace "expo.modules.handtracker"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  def camerax_version = "1.5.0-rc01"
  def mediapipe_version = "0.10.20"

  implementation "androidx.camera:camera-core:${camerax_version}"
  implementation "androidx.camera:camera-camera2:${camerax_version}"
  implementation "androidx.camera:camera-lifecycle:${camerax_version}"
  implementation "androidx.camera:camera-view:${camerax_version}"
  implementation "com.google.mediapipe:tasks-vision:${mediapipe_version}"
}
